try{
    console.log('não deu erro');
} catch(error){
    console.log('arrumando o erro');
} finally{
    console.log('só testes');
}